fix warn scripts

diff --git a/mulle-bootstrap b/mulle-bootstrap
--- a/mulle-bootstrap
+++ b/mulle-bootstrap
@@ -29,7 +29,7 @@
 #   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 #   POSSIBILITY OF SUCH DAMAGE.
 
-VERSION=0.8
+VERSION=0.8.1
 
 #
 # This is the main user interface to mulle-bootstrap
@@ -136,9 +136,6 @@ EOF
 command=${1:-"bootstrap"}
 shift
 
-. mulle-bootstrap-warn-scripts.sh
-
-
 
 bootstrap()
 {
@@ -156,7 +153,7 @@ bootstrap()
       . install.sh "$@"
       export MULLE_BOOTSTRAP=mulle-bootstrap
    else
-      warn_scripts "${BOOTSTRAP_SUBDIR}"  || fail "Ok, aborted."
+      mulle-bootstrap-warn-scripts.sh "${BOOTSTRAP_SUBDIR}"  || fail "Ok, aborted."
    fi
 
    if [ "${DONT_RECURSE}" = "" ]
