Added mulle-brew command, which is a restricted form of mulle-bootstrap.

diff --git a/mulle-bootstrap b/mulle-bootstrap
--- a/mulle-bootstrap
+++ b/mulle-bootstrap
@@ -33,7 +33,6 @@ MULLE_BOOTSTRAP_VERSION_MINOR=0
 MULLE_BOOTSTRAP_VERSION_PATCH=0
 
 MULLE_BOOTSTRAP_VERSION="${MULLE_BOOTSTRAP_VERSION_MAJOR}.${MULLE_BOOTSTRAP_VERSION_MINOR}.${MULLE_BOOTSTRAP_VERSION_PATCH}"
-MULLE_BOOTSTRAP_FAIL_PREFIX="mulle-bootstrap"
 
 #
 # This is the main user interface to mulle-bootstrap
@@ -46,7 +45,59 @@ trap_fail()
 }
 
 
-usage()
+bootstrap_technical_option_usage()
+{
+   if [ ! -z "${VERBOSE}" -o ! -z "${MULLE_BOOTSTRAP_TRACE}" ]
+   then
+      cat <<EOF
+   -t        : enable shell trace
+   -te       : trace execution
+   -tm       : trace merge and dependencies
+   -tss      : also trace scripts
+   -tst      : also trace settings
+   -tsp      : also trace path functionality
+   -vv       : very verbose
+   -vvv      : extremely vebose
+   -s        : be silent
+EOF
+   fi
+}
+
+
+mulle_brew_usage()
+{
+   cat <<EOF
+usage: mulle-brew [flags] [command] [options]
+ Flags:
+   -n        : do nothing creative or destructive
+   -v        : -v to be more verbose (-vv or -vvv for more verbosity)
+EOF
+
+   bootstrap_technical_option_usage
+
+   cat <<EOF
+
+ Commands:
+   install   : fetches brews
+   update    : update brew
+   upgrade   : upgrade brew fomulae
+   init      : initializes a bootstrap project
+
+ Options are command specific. Use mulle-brew <command> -h for help.
+EOF
+
+   if [ "${UNAME}" = 'darwin' ]
+   then
+      cat <<EOF
+   xcode     : setup xcodeproj settings
+EOF
+   fi
+
+   exit 1
+}
+
+
+mulle_bootstrap_usage()
 {
    cat <<EOF
 usage: mulle-bootstrap [flags] [command] [options]
@@ -56,26 +107,11 @@ usage: mulle-bootstrap [flags] [command] [options]
    -f        : force operation
    -n        : do nothing creative or destructive
    -v        : -v to be more verbose (-vv or -vvv for more verbosity)
+   -V        : verbose build
    -DKEY=VAL : define local key/value C style
 EOF
 
-   if [ ! -z "${VERBOSE}" -o ! -z "${MULLE_BOOTSTRAP_TRACE}" ]
-   then
-      cat <<EOF
-   -l        : be more optimistic and faster
-   -ig       : ignore .repos/.graveyard
-   -te       : trace execution
-   -tm       : trace merge and dependencies
-   -tss      : also trace scripts
-   -tst      : also trace settings
-   -tsp      : also trace path functionality
-   -t        : trace execution
-   -vv       : very verbose
-   -vvv      : extremely vebose
-   -s        : be silent
-   -V        : verbose build
-EOF
-   fi
+   bootstrap_technical_option_usage
 
    cat <<EOF
 
@@ -102,8 +138,6 @@ EOF
 EOF
    fi
 
-cat <<EOF
-EOF
    exit 1
 }
 
@@ -220,7 +254,7 @@ bootstrap_execute_in_master()
    [ -d "${master}" ] || fail "master \"${master}\" is gone ($masterpath)"
 
    (
-      cd "${master}" && mulle-bootstrap "$@"
+      cd "${master}" && "${MULLE_BOOTSTRAP_EXECUTABLE}" "$@"
    ) || fail "master failed"
 }
 
@@ -235,7 +269,7 @@ bootstrap_libexec_path()
    exedir="`dirname "$1"`"
    exedirpath="`( cd "${exedir}" ; pwd -P )`" || fail "failed to get pwd"
    prefix="`dirname "${exedirpath}"`"
-   libexecpath="${prefix}/libexec/mulle-bootstrap-3"
+   libexecpath="${prefix}/libexec/mulle-bootstrap"
 
    if [ ! -x "${libexecpath}/mulle-bootstrap-functions.sh" ]
    then
@@ -259,13 +293,9 @@ bootstrap_dump_env()
 }
 
 
-bootstrap_main()
+bootstrap_init()
 {
-   local command
    local libexecpath
-   local ps4string
-
-   BOOTSTRAP_DIR=.bootstrap
 
    libexecpath="`bootstrap_libexec_path "$0"`"
    if [ -z "${libexecpath}" ]
@@ -314,154 +344,11 @@ bootstrap_main()
    trap trap_fail INT
 
    source_environment
-   #
-   # simple option handling
-   #
-   while [ $# -ne 0 ]
-   do
-      case "$1" in
-         -a|--prefer-origin)
-            MULLE_BOOTSTRAP_ANSWER="NO"
-          ;;
-
-         -y|--prefer-local)
-            MULLE_BOOTSTRAP_ANSWER="YES"
-         ;;
-
-         -f|--force-fetch)
-            MULLE_BOOTSTRAP_DIRTY_HARRY="NO"
-         ;;
-
-         -n|--dry-run)
-            MULLE_EXECUTOR_DRY_RUN="YES"
-         ;;
-
-         -l|--optimistic|--lucky)
-            MULLE_BOOTSTRAP_OPTIMISTIC="YES"
-         ;;
-
-         -ig|--ignore-graveyard)
-            MULLE_BOOTSTRAP_IGNORE_GRAVEYARD="YES"
-         ;;
-
-         -te|--trace-execution)
-            MULLE_EXECUTOR_TRACE="YES"
-         ;;
-
-         -tm|--trace-settings-merge)
-            [ "${MULLE_BOOTSTRAP_TRACE}" = "1848" ] || fail "option \"$1\" must be specified after -t"
-            MULLE_BOOTSTRAP_TRACE_MERGE="YES"
-         ;;
-
-         -tsc|--trace-show-scripts)
-            [ "${MULLE_BOOTSTRAP_TRACE}" = "1848" ] || fail "option \"$1\" must be specified after -t"
-            MULLE_BOOTSTRAP_TRACE_SCRIPT_CALLS="YES"
-         ;;
-
-         -tsr|--trace-show-resolver)
-            [ "${MULLE_BOOTSTRAP_TRACE}" = "1848" ] || fail "option \"$1\" must be specified after -t"
-            MULLE_BOOTSTRAP_RESOLVER_FLIP_X="NO"
-         ;;
-
-         -tss|--trace-show-settings)
-            [ "${MULLE_BOOTSTRAP_TRACE}" = "1848" ] || fail "option \"$1\" must be specified after -t"
-            MULLE_BOOTSTRAP_SETTINGS_FLIP_X="NO"
-         ;;
-
-         -tsp|--trace-show-paths)
-            [ "${MULLE_BOOTSTRAP_TRACE}" = "1848" ] || fail "option \"$1\" must be specified after -t"
-            MULLE_BOOTSTRAP_PATHS_FLIP_X="NO"
-         ;;
-
-         -tp|--trace-profile)
-            [ "${MULLE_BOOTSTRAP_TRACE}" = "1848" ] || fail "option \"$1\" must be specified after -t"
-            case "${UNAME}" in
-               linux)
-                  ps4string='$(date "\+ +%s.%N (${BASH_SOURCE[1]##*/}:$LINENO)")'
-               ;;
-               *)
-                  ps4string='$(date "\+ +%s (${BASH_SOURCE[1]##*/}:$LINENO)")'
-               ;;
-            esac
-         ;;
-
-         -tpo|--trace-postponed)
-            [ "${MULLE_BOOTSTRAP_TRACE}" = "1848" ] || fail "option \"$1\" must be specified after -t"
-            MULLE_BOOTSTRAP_POSTPONE_TRACE=YES
-         ;;
-
-         -tfpwd|--trace-full-pwd)
-            [ "${MULLE_BOOTSTRAP_TRACE}" = "1848" ] || fail "option \"$1\" must be specified after -t"
-            ps4string='${BASH_SOURCE[1]##*/}:$LINENO \"\w\"'
-         ;;
+}
 
 
-         -tpwd|--trace-pwd)
-            [ "${MULLE_BOOTSTRAP_TRACE}" = "1848" ] || fail "option \"$1\" must be specified after -t"
-            ps4string='${BASH_SOURCE[1]##*/}:$LINENO \".../\W\"'
-         ;;
-
-         -t|--trace)
-            MULLE_BOOTSTRAP_TRACE="1848"
-            COPYMOVEFLAGS="-v"
-            GITOPTIONS="`concat "${GITOPTIONS}" "-v"`"
-            MULLE_BOOTSTRAP_PATHS_FLIP_X="YES"
-            MULLE_BOOTSTRAP_RESOLVER_FLIP_X="YES"
-            MULLE_BOOTSTRAP_SETTINGS_FLIP_X="YES"
-            MULLE_BOOTSTRAP_TRACE_SCRIPT_CALLS="NO"
-            ps4string='${BASH_SOURCE[1]##*/}:$LINENO'
-         ;;
-
-         -v|--verbose)
-            MULLE_BOOTSTRAP_TRACE="VERBOSE"
-            COPYMOVEFLAGS="-v"
-            GITOPTIONS="`concat "${GITOPTIONS}" "-v"`"
-         ;;
-
-         -vv|--very-verbose)
-            MULLE_BOOTSTRAP_TRACE="FLUFF"
-            COPYMOVEFLAGS="-v"
-            GITOPTIONS="`concat "${GITOPTIONS}" "-v"`"
-         ;;
-
-         -vvv|--very-verbose-with-settings)
-            MULLE_BOOTSTRAP_TRACE="TRACE"
-            COPYMOVEFLAGS="-v"
-            GITOPTIONS="`concat "${GITOPTIONS}" "-v"`"
-         ;;
-
-         -s|--silent)
-            MULLE_BOOTSTRAP_TRACE=
-            MULLE_BOOTSTRAP_TERSE="YES"
-            GITOPTIONS="`concat "${GITOPTIONS}" "-v"`"
-         ;;
-
-         -h|--help)
-            usage
-         ;;
-
-         -D*)  # just like C
-            # define key values (by putting them into .bootstrap.local)
-            define_local_keyvalue "`echo "$1" | sed s'/^-D[ ]*//'`"
-         ;;
-
-         -V|--verbose-build)
-            MULLE_BOOTSTRAP_VERBOSE_BUILD="YES"
-         ;;
-
-         -*)
-            log_error "${MULLE_BOOTSTRAP_FAIL_PREFIX}: Unknown flag \"$1\""
-            usage
-         ;;
-
-         *)
-            break
-         ;;
-      esac
-
-      shift
-   done
-
+bootstrap_setup_trace()
+{
    case "${MULLE_BOOTSTRAP_TRACE}" in
       VERBOSE)
          MULLE_BOOTSTRAP_FLUFF="NO"
@@ -514,6 +401,218 @@ bootstrap_main()
          fi
       ;;
    esac
+}
+
+
+bootstrap_technical_options()
+{
+   case "$1" in
+      -n|--dry-run)
+         MULLE_EXECUTOR_DRY_RUN="YES"
+      ;;
+
+      -te|--trace-execution)
+         MULLE_EXECUTOR_TRACE="YES"
+      ;;
+
+      -tm|--trace-settings-merge)
+         [ "${MULLE_BOOTSTRAP_TRACE}" = "1848" ] || fail "option \"$1\" must be specified after -t"
+         MULLE_BOOTSTRAP_TRACE_MERGE="YES"
+      ;;
+
+      -tsc|--trace-show-scripts)
+         [ "${MULLE_BOOTSTRAP_TRACE}" = "1848" ] || fail "option \"$1\" must be specified after -t"
+         MULLE_BOOTSTRAP_TRACE_SCRIPT_CALLS="YES"
+      ;;
+
+      -tsr|--trace-show-resolver)
+         [ "${MULLE_BOOTSTRAP_TRACE}" = "1848" ] || fail "option \"$1\" must be specified after -t"
+         MULLE_BOOTSTRAP_RESOLVER_FLIP_X="NO"
+      ;;
+
+      -tss|--trace-show-settings)
+         [ "${MULLE_BOOTSTRAP_TRACE}" = "1848" ] || fail "option \"$1\" must be specified after -t"
+         MULLE_BOOTSTRAP_SETTINGS_FLIP_X="NO"
+      ;;
+
+      -tsp|--trace-show-paths)
+         [ "${MULLE_BOOTSTRAP_TRACE}" = "1848" ] || fail "option \"$1\" must be specified after -t"
+         MULLE_BOOTSTRAP_PATHS_FLIP_X="NO"
+      ;;
+
+      -tp|--trace-profile)
+         [ "${MULLE_BOOTSTRAP_TRACE}" = "1848" ] || fail "option \"$1\" must be specified after -t"
+         case "${UNAME}" in
+            linux)
+               ps4string='$(date "\+ +%s.%N (${BASH_SOURCE[1]##*/}:$LINENO)")'
+            ;;
+            *)
+               ps4string='$(date "\+ +%s (${BASH_SOURCE[1]##*/}:$LINENO)")'
+            ;;
+         esac
+      ;;
+
+      -tpo|--trace-postponed)
+         [ "${MULLE_BOOTSTRAP_TRACE}" = "1848" ] || fail "option \"$1\" must be specified after -t"
+         MULLE_BOOTSTRAP_POSTPONE_TRACE=YES
+      ;;
+
+      -tfpwd|--trace-full-pwd)
+         [ "${MULLE_BOOTSTRAP_TRACE}" = "1848" ] || fail "option \"$1\" must be specified after -t"
+         ps4string='${BASH_SOURCE[1]##*/}:$LINENO \"\w\"'
+      ;;
+
+
+      -tpwd|--trace-pwd)
+         [ "${MULLE_BOOTSTRAP_TRACE}" = "1848" ] || fail "option \"$1\" must be specified after -t"
+         ps4string='${BASH_SOURCE[1]##*/}:$LINENO \".../\W\"'
+      ;;
+
+      -t|--trace)
+         MULLE_BOOTSTRAP_TRACE="1848"
+         COPYMOVEFLAGS="-v"
+         GITOPTIONS="`concat "${GITOPTIONS}" "-v"`"
+         MULLE_BOOTSTRAP_PATHS_FLIP_X="YES"
+         MULLE_BOOTSTRAP_RESOLVER_FLIP_X="YES"
+         MULLE_BOOTSTRAP_SETTINGS_FLIP_X="YES"
+         MULLE_BOOTSTRAP_TRACE_SCRIPT_CALLS="NO"
+         ps4string='${BASH_SOURCE[1]##*/}:$LINENO'
+      ;;
+
+      -v|--verbose)
+         MULLE_BOOTSTRAP_TRACE="VERBOSE"
+         COPYMOVEFLAGS="-v"
+         GITOPTIONS="`concat "${GITOPTIONS}" "-v"`"
+      ;;
+
+      -vv|--very-verbose)
+         MULLE_BOOTSTRAP_TRACE="FLUFF"
+         COPYMOVEFLAGS="-v"
+         GITOPTIONS="`concat "${GITOPTIONS}" "-v"`"
+      ;;
+
+      -vvv|--very-verbose-with-settings)
+         MULLE_BOOTSTRAP_TRACE="TRACE"
+         COPYMOVEFLAGS="-v"
+         GITOPTIONS="`concat "${GITOPTIONS}" "-v"`"
+      ;;
+
+      -s|--silent)
+         MULLE_BOOTSTRAP_TRACE=
+         MULLE_BOOTSTRAP_TERSE="YES"
+         GITOPTIONS="`concat "${GITOPTIONS}" "-v"`"
+      ;;
+
+      *)
+         return 1
+      ;;
+   esac
+
+   return 0
+}
+
+
+bootstrap_defer_to_master_if_needed()
+{
+   local command="$1"
+
+   #
+   # if we have a.bootstrap.local/minion file then
+   # some commands can't run, and some commands are re-executed in master
+   # and some commands (like fetch and clean) are executed locally AND in the
+   # master
+   #
+   local masterpath
+
+   masterpath="${BOOTSTRAP_DIR}.local/master"
+   if [ -e "${masterpath}" ]
+   then
+      case "${command}" in
+         build)
+            log_info "Minion .bootstrap: defer to master for execution"
+            exec bootstrap_execute_in_master "${masterpath}" "$@"
+         ;;
+
+         fetch|install|upgrade|update|clean|dist-clean)
+            log_info "Minion .bootstrap: execute partly in master"
+            bootstrap_execute_in_master "${masterpath}" "$@"
+            EMBEDDED_ONLY=YES
+         ;;
+
+         git|setup-xcode|xcode|tag|version)
+            log_verbose "Minion .bootstrap: execute locally"
+         ;;
+
+         *)
+            fail "This is a minion bootstrap project (${masterpath}), can't continue"
+         ;;
+      esac
+   fi
+}
+
+
+bootstrap_main()
+{
+   local command
+   local ps4string
+
+   bootstrap_init
+   #
+   # simple option handling
+   #
+   while [ $# -ne 0 ]
+   do
+      if bootstrap_technical_options "$1"
+      then
+         shift
+         continue
+      fi
+
+      case "$1" in
+         -a|--prefer-origin)
+            MULLE_BOOTSTRAP_ANSWER="NO"
+          ;;
+
+         -y|--prefer-local)
+            MULLE_BOOTSTRAP_ANSWER="YES"
+         ;;
+
+         -f|--force-fetch)
+            MULLE_BOOTSTRAP_DIRTY_HARRY="NO"
+         ;;
+
+         -ig|--ignore-graveyard)
+            MULLE_BOOTSTRAP_IGNORE_GRAVEYARD="YES"
+         ;;
+
+         -h|--help)
+            mulle_bootstrap_usage
+         ;;
+
+         -D*)  # just like C
+            # define key values (by putting them into .bootstrap.local)
+            define_local_keyvalue "`echo "$1" | sed s'/^-D[ ]*//'`"
+         ;;
+
+         -V|--verbose-build)
+            MULLE_BOOTSTRAP_VERBOSE_BUILD="YES"
+         ;;
+
+         -*)
+            log_error "${MULLE_BOOTSTRAP_FAIL_PREFIX}: Unknown flag \"$1\""
+            usage
+         ;;
+
+         *)
+            break
+         ;;
+      esac
+
+      shift
+   done
+
+   bootstrap_setup_trace
+
 
    if [ "${MULLE_EXECUTOR_DRY_RUN}" = "YES" ]
    then
@@ -544,38 +643,7 @@ bootstrap_main()
          ;;
       esac
    else
-      #
-      # if we have a.bootstrap.local/minion file then
-      # some commands can't run, and some commands are re-executed in master
-      # and some commands (like fetch and clean) are executed locally AND in the
-      # master
-      #
-      local masterpath
-
-      masterpath="${BOOTSTRAP_DIR}.local/master"
-      if [ -e "${masterpath}" ]
-      then
-         case "${command}" in
-            build)
-               log_info "Minion .bootstrap: defer to master for execution"
-               exec bootstrap_execute_in_master "${masterpath}" "$@"
-            ;;
-
-            fetch|install|upgrade|update|clean|dist-clean)
-               log_info "Minion .bootstrap: execute partly in master"
-               bootstrap_execute_in_master "${masterpath}" "$@"
-               EMBEDDED_ONLY=YES
-            ;;
-
-            git|setup-xcode|xcode|tag|version)
-               log_verbose "Minion .bootstrap: execute locally"
-            ;;
-
-            *)
-               fail "This is a minion bootstrap project (${masterpath}), can't continue"
-            ;;
-         esac
-      fi
+      bootstrap_defer_to_master_if_needed "$@"
 
       if [ "${MULLE_BOOTSTRAP_DIRTY_HARRY}" != "NO" ]
       then
@@ -591,7 +659,7 @@ bootstrap_main()
       fi
    fi
 
-   MULLE_BOOTSTRAP_FAIL_PREFIX="mulle-bootstrap ${command}"
+   MULLE_BOOTSTRAP_FAIL_PREFIX="${MULLE_BOOTSTRAP_EXECUTABLE} ${command}"
 
    case "${command}" in
       bootstrap|nomagic)
@@ -700,7 +768,176 @@ bootstrap_main()
    esac
 }
 
-bootstrap_main "$@"
+
+brew_main()
+{
+   local command
+   local ps4string
+
+   bootstrap_init
+   #
+   # simple option handling
+   #
+   while [ $# -ne 0 ]
+   do
+      if bootstrap_technical_options "$1"
+      then
+         shift
+         continue
+      fi
+
+      case "$1" in
+         -h|--help)
+            mulle_brew_usage
+         ;;
+         -*)
+            log_error "${MULLE_BOOTSTRAP_FAIL_PREFIX}: Unknown flag \"$1\""
+            usage
+         ;;
+
+         *)
+            break
+         ;;
+      esac
+
+      shift
+   done
+
+   bootstrap_setup_trace
+
+   if [ "${MULLE_EXECUTOR_DRY_RUN}" = "YES" ]
+   then
+      log_trace "Dry run is active."
+   fi
+
+   # source in environment now
+
+   local_environment_main
+
+   #
+   # some commands only run when we have a .bootstrap folder
+   #
+   command=${1:-"install"}
+   [ $# -eq 0 ] || shift
+
+   if [ ! -d "${BOOTSTRAP_DIR}" ]
+   then
+      case "$1" in
+         -h|--help)
+         ;;
+
+         *)
+            case "${command}" in
+            dist|clean|dist-clean|install|upgrade|update|setup-xcode|xcode)
+               fail "There is no ${BOOTSTRAP_DIR} folder here, can't continue"
+            esac
+         ;;
+      esac
+   else
+      bootstrap_defer_to_master_if_needed "$@"
+   fi
+
+   MULLE_BOOTSTRAP_FAIL_PREFIX="${MULLE_BOOTSTRAP_EXECUTABLE} ${command}"
+
+   case "${command}" in
+      build)
+         . mulle-bootstrap-build.sh
+
+         build_main "$@" || exit 1
+      ;;
+
+      clean)
+         . mulle-bootstrap-clean.sh
+
+         clean_main "$@" || exit 1
+      ;;
+
+      config)
+         . mulle-bootstrap-settings.sh
+
+         config_main "$@" || exit 1
+      ;;
+
+      setting)
+         . mulle-bootstrap-settings.sh
+
+         setting_main "$@" || exit 1
+      ;;
+
+      dist)
+         . mulle-bootstrap-clean.sh
+
+         clean_main "dist" || exit 1
+      ;;
+
+      init)
+         . mulle-bootstrap-init.sh
+
+         init_main "$@" || exit 1
+      ;;
+
+      install|fetch)
+         . mulle-bootstrap-brew.sh
+
+         brew_install_main "$@" || exit 1
+      ;;
+
+      library-path)
+         echo "$PATH" | tr ':' '\012' | head -1
+         return 0
+      ;;
+
+      update)
+         . mulle-bootstrap-brew.sh
+
+         brew_update_main "$@" || exit 1
+      ;;
+
+      upgrade)
+         . mulle-bootstrap-brew.sh
+
+         brew_upgrade_main "$@" || exit 1
+      ;;
+
+      setup-xcode|xcode)
+         . mulle-bootstrap-xcode.sh
+
+         MULLE_BOOTSTRAP_FAIL_PREFIX="mulle-bootstrap xcode"
+         xcode_main "$@" || exit 1
+      ;;
+
+      uname)
+         echo "${UNAME}"
+         exit 0
+      ;;
+
+      version)
+         echo "${MULLE_BOOTSTRAP_VERSION}"
+         return 0
+      ;;
+
+      *)
+         log_error "${MULLE_BOOTSTRAP_FAIL_PREFIX}: Unknown command \"${command}\""
+         usage
+      ;;
+   esac
+}
+
+#
+# service both names
+#
+MULLE_BOOTSTRAP_EXECUTABLE="`basename -- "$0"`"
+MULLE_BOOTSTRAP_FAIL_PREFIX="${MULLE_BOOTSTRAP_EXECUTABLE}"
+
+case "${MULLE_BOOTSTRAP_EXECUTABLE}" in
+   "mulle-brew")
+      brew_main "$@"
+   ;;
+
+   "mulle-bootstrap")
+      bootstrap_main "$@"
+   ;;
+esac
 
 trap - TERM EXIT
 
